spring:
  datasource:
    druid:
      #    driver-class-name: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: 你的数据库账号
      password: 你的数据库密码
      url: jdbc:mysql://您的数据库IP:3306/myapps?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
      # Druid StatViewServlet配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
  jpa:
    # 生产环境设置为false
    show-sql: true

#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB
#      enabled: true
app:
  base:
    open-auth: false
    #    file-url-host: http://stc.wangjiayang.cn/blog
    file-url-host: /stc
    #真实路径
    upload-path-prefix: /data/stc/blog
    #临时路径
    upload-temp-prefix: /data/temp
    file-path-prefix: /files
    #文件导入路径
    #    file-import: /import
    #文件导出路径
#    file-export: /export
